<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Sales Report - {{ $startDate }} to {{ $endDate }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
        }

        .header .subtitle {
            font-size: 16px;
            color: #666;
        }

        .summary {
            margin-bottom: 20px;
        }

        .summary-box {
            border: 1px solid #ddd;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
        }

        .summary-box h3 {
            margin: 0 0 5px 0;
            font-size: 14px;
        }

        .summary-box .value {
            font-size: 18px;
            font-weight: bold;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table th,
        table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        table th {
            background-color: #f5f5f5;
            font-weight: bold;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }

        .text-right {
            text-align: right;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ setting('site_name') }}</h1>
        <h3>Sales Report</h3>
        <div class="subtitle">{{ $startDate }} to {{ $endDate }}</div>
        <div>Generated on: {{ now()->format('Y-m-d H:i:s') }}</div>
    </div>

    <div class="summary">
        <table style="margin-bottom: 20px;">
            <tr>
                <td style="width: 33%;" class="summary-box">
                    <h3>Total Sales</h3>
                    <div class="value">${{ number_format($totalSales, 2) }}</div>
                </td>
                <td style="width: 33%;" class="summary-box">
                    <h3>Total Orders</h3>
                    <div class="value">{{ $totalOrders }}</div>
                </td>
                <td style="width: 33%;" class="summary-box">
                    <h3>Average Order Value</h3>
                    <div class="value">${{ number_format($avgOrderValue, 2) }}</div>
                </td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th>Order #</th>
                <th>Date</th>
                <th>Customer Email</th>
                <th>Items</th>
                <th class="text-right">Subtotal</th>
                <th class="text-right">Shipping</th>
                <th class="text-right">Discount</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($orders as $order)
                <tr>
                    <td>{{ $order->order_number }}</td>
                    <td>{{ $order->created_at->format('M d, Y') }}</td>
                    <td>{{ $order->customer_email }}</td>
                    <td>{{ $order->items->count() }}</td>
                    <td class="text-right">${{ number_format($order->subtotal, 2) }}</td>
                    <td class="text-right">${{ number_format($order->shipping_cost, 2) }}</td>
                    <td class="text-right">${{ number_format($order->discount_amount, 2) }}</td>
                    <td class="text-right">${{ number_format($order->total_amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="font-weight: bold;">
                <td colspan="4" class="text-right">TOTALS:</td>
                <td class="text-right">${{ number_format($orders->sum('subtotal'), 2) }}</td>
                <td class="text-right">${{ number_format($orders->sum('shipping_cost'), 2) }}</td>
                <td class="text-right">${{ number_format($orders->sum('discount_amount'), 2) }}</td>
                <td class="text-right">${{ number_format($orders->sum('total_amount'), 2) }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Report generated by {{ \app\Models\User::find(auth()->id())->name }} on {{ now()->format('F j, Y') }}
    </div>
</body>

</html>
